### ISSUE TITLE
Combining apt and fzf

### ISSUE THREAD

**Issue by kam3k** [jmdaly/dotfiles#3]
I've been toying with using `fzf` to browse and install packages with `apt`. I thought you may be interested in the result, try it out:

`apt-cache search '' | sort | cut --delimiter ' ' --fields 1 | fzf --multi --cycle --reverse --preview 'apt-cache show {1}' | xargs -r sudo apt install -y`

This opens `fzf` and lets you fuzzy search packages, and shows details of the currently selected package with `apt-cache show` in a preview window. Press escape to cancel, or select a package and press enter to install. I've mapped the above to the alias `a`. It's super fast; it essentially instantly lists the 60,000 packages in debian.

**Comment by jmdaly** [comment]
That's really cool! I just tried it out. I'll definitely throw this in my zshrc. Thanks for sharing!

**Comment by rosejn** [comment]
Nice, just what I was looking for.  Thanks!

**Comment by macizomedia** [comment]
Just change it to work with pacman!

Also works, but might need some tweaks for installing the package

```bash
pacman -Ss '' | sort | cut --delimiter ' ' --fields 1 | fzf --multi --cycle --reverse --preview 'pacman -Ss {1}' | xargs -r sudo pacman -S
```
